unclassified:
  jiraGlobalConfiguration:
    sites:
    - credentialsId: "JIRA_PLUGIN"
      recordScmChanges: true
      supportsWikiStyleComment: true
      updateJiraIssueForAllStatus: true
      url: "https://jira.nuxeo.com/"

credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          description: "JIRA plugin"
          id: "JIRA_PLUGIN"
          scope: GLOBAL
          username: "hudson"
          password: "${JIRA_PASSWORD}"
